// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxthgrywznyhaezsentl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4dGhncnl3em55aGFlenNlbnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMTA4MzksImV4cCI6MjA2MDY4NjgzOX0.99WdPW5xhrwam12j0r42ntcj8-FHuCc0T3LHBwhr7kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);